/*
 * File: app/store/EpisodesStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.EpisodesStore', {
    extend: 'Ext.data.Store',

    config: {
        storeId: 'EpisodesStore',
        fields: [
            {
                name: 'episode_id'
            },
            {
                name: 'episode_name'
            },
            {
                name: 'episode_thumbnail'
            },
            {
                name: 'episode_html'
            },
            {
                dateFormat: 'U',
                name: 'episode_date',
                type: 'date'
            },
            {
                name: 'episode_duration'
            },
            {
                name: 'episode_type'
            },
            {
                name: 'episode_added'
            },
            {
                name: 'episode_description'
            },
            {
                name: 'episode_played'
            },
            {
                name: 'episode_time_played'
            }
        ],
        proxy: {
            type: 'ajax',
            url: 'episodes.php',
            reader: {
                type: 'json',
                rootProperty: 'rows'
            }
        }
    }
});