/*
 * File: app/store/LibraryStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.LibraryStore', {
    extend: 'Ext.data.Store',

    config: {
        storeId: 'LibraryStore',
        fields: [
            {
                name: 'podcast_id'
            },
            {
                name: 'podcast_name'
            },
            {
                name: 'podcast_thumbnail'
            },
            {
                name: 'podcast_type'
            },
            {
                name: 'podcast_description'
            },
            {
                name: 'podcast_category'
            },
            {
                name: 'podcast_subscribe'
            },
            {
                name: 'episodes'
            }
        ],
        proxy: {
            type: 'ajax',
            url: 'library.php',
            reader: {
                type: 'json',
                rootProperty: 'rows'
            }
        }
    }
});