/*
 * File: app/store/PodcastStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.PodcastStore', {
    extend: 'Ext.data.Store',
    alias: 'store.podcaststore',

    config: {
        storeId: 'PodcastStore',
        fields: [
            {
                name: 'podcast_id'
            },
            {
                name: 'podcast_name'
            },
            {
                name: 'podcast_thumbnail'
            },
            {
                name: 'podcast_type'
            },
            {
                name: 'podcast_description'
            },
            {
                name: 'podcast_category'
            },
            {
                name: 'podcast_subscribe'
            },
            {
                name: 'episodes'
            }
        ],
        proxy: {
            type: 'ajax',
            url: 'http://app.dev/podcast/mypodcast.php',
            reader: {
                type: 'json',
                rootProperty: 'rows'
            }
        },
        listeners: [
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ]
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        var unwatched = 0;
        store.each(function(rec) {        
            var epi = rec.get('episodes');
            unwatched+= epi.unwatched;
        });

        Ext.ComponentQuery.query('#unplayedbtnright')[0].setText(unwatched);
    }

});