/*
 * File: app/store/UnplayedStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.UnplayedStore', {
    extend: 'Ext.data.Store',
    alias: 'store.unplayedstore',

    config: {
        autoLoad: true,
        data: [
            {
                photo_url: 'http://media2.ak.yelpcdn.com/bpthumb/LPp9JaaGjXYIhIxIIoBI0A/ms',
                name: 'Sunny\'s Bar',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media3.ak.yelpcdn.com/bpthumb/Tz0vtUWDjb_u-XkrRbv5EA/ms',
                name: 'Duff\'s Brooklyn',
                type: 'movie',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media4.ak.yelpcdn.com/bpthumb/wv7XY2ENy4HD6ZufRCnXvA/ms',
                name: 'Vin Sur Vingt',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media3.ak.yelpcdn.com/bpthumb/JAifIRY9JIV_Z5IrrD102Q/ms',
                name: 'Lucky 13 Saloon',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media2.ak.yelpcdn.com/bpthumb/KGV5uYP6ptUfls13ZlsEfg/ms',
                name: 'Sunny\'s Bar',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media1.ak.yelpcdn.com/bpthumb/rJjRHfqg2n9cd2Uq3oRftQ/ms',
                name: 'Duff\'s Brooklyn',
                type: 'movie',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media2.ak.yelpcdn.com/bpthumb/hBZ6N-xVIR6kWM1JKBR-iw/ms',
                name: 'Vin Sur Vingt',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media4.ak.yelpcdn.com/bpthumb/BxjbE1g3snRu6d0dHD_V6Q/ms',
                name: 'Lucky 13 Saloon',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media3.ak.yelpcdn.com/bpthumb/K_23zz6O6SeN1gX8Y5h8hA/ms',
                name: 'Sunny\'s Bar',
                type: 'movie',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media1.ak.yelpcdn.com/bpthumb/bJT-SPJrjTIi6K8ehqwnXQ/ms',
                name: 'Duff\'s Brooklyn',
                type: 'movie',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media3.ak.yelpcdn.com/bpthumb/JAifIRY9JIV_Z5IrrD102Q/ms',
                name: 'Vin Sur Vingt',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media1.ak.yelpcdn.com/bpthumb/KtdHatgh-koBoQ9HrpNWLA/ms',
                name: 'Lucky 13 Saloon',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media1.ak.yelpcdn.com/bpthumb/d_osp98Jw_sdLNyOqeitbQ/ms',
                name: 'Sunny\'s Bar',
                type: 'movie',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media1.ak.yelpcdn.com/bpthumb/rJjRHfqg2n9cd2Uq3oRftQ/ms',
                name: 'Duff\'s Brooklyn',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media2.ak.yelpcdn.com/bpthumb/hBZ6N-xVIR6kWM1JKBR-iw/ms',
                name: 'Vin Sur Vingt',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            {
                photo_url: 'http://media4.ak.yelpcdn.com/bpthumb/BxjbE1g3snRu6d0dHD_V6Q/ms',
                name: 'Lucky 13 Saloon',
                type: 'music',
                date: '12.02.2013 12:50'
            },
            
        ],
        storeId: 'UnplayedStore',
        fields: [
            {
                name: 'photo_url'
            },
            {
                name: 'name'
            },
            {
                name: 'type'
            },
            {
                name: 'date'
            }
        ]
    }
});