/*
 * File: app/view/Category.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Category', {
    extend: 'Ext.Container',
    alias: 'widget.category',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                itemId: 'mylist4',
                scrollable: true,
                itemTpl: [
                    '<div class="list-info">',
                    '	<div class="podcast-name">{name}</div>',
                    '    <tpl if="type == \'music\'">',
                    '        <div class="music-box">',
                    '            <span class="music-icon-unplayed"></span><span class="music-date">{date}</span>',
                    '        </div>',
                    '    <tpl else>',
                    '        <div class="video-box">',
                    '            <span class="video-icon-grey"></span><span class="video-date">{date}</span>',
                    '        </div>',
                    '    </tpl>',
                    '</div>',
                    ''
                ],
                store: 'UnplayedStore',
                itemHeight: 70
            }
        ],
        listeners: [
            {
                fn: 'onMylist4ItemTap',
                event: 'itemtap',
                delegate: '#mylist4'
            }
        ]
    },

    onMylist4ItemTap: function(dataview, index, target, record, e, eOpts) {
        var me = this;
        var nav = Ext.ComponentQuery.query('#nav')[0];
        nav.push({
            xtype: 'library',
            title: 'Podcasts Library'
        });
    }

});