/*
 * File: app/view/Episodes.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Episodes', {
    extend: 'Ext.Container',
    alias: 'widget.episodes',

    config: {
        itemId: 'episodes',
        layout: {
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                flex: 1,
                docked: 'top',
                style: 'border: none;\r\nbackground: #8fced6;',
                items: [
                    {
                        xtype: 'label',
                        html: 'Daft Punk Podcasts',
                        style: 'color: #000;\r\nfont-size: 14px;',
                        ui: ''
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        style: 'background: #fff;\r\ncolor: #8fced6;\r\nborder: none;',
                        text: 'Subscribe'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 0.6,
                docked: 'top',
                height: 170,
                html: '<p> 	<div style="float: left; text-align:center;"> 	    <img width="150px" height="150px" src="http://media2.ak.yelpcdn.com/bpthumb/LPp9JaaGjXYIhIxIIoBI0A/ms" style="margin: 5px 10px 5px 5px;"> 	    <div><span style="float: none" class="music-toal">5</span><span style="float: none" class="video-toal">10</span></div> 	</div> 	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor nisi ut aliquip ex ea commodo consequat.  more  </p>',
                style: 'color: #555555;\r\nfont-size: 12px;',
                ui: '',
                scrollable: 'vertical'
            },
            {
                xtype: 'list',
                flex: 1,
                itemId: 'mylist2',
                scrollable: 'vertical',
                itemTpl: [
                    '<img class="photo shadow" src="{photo_url}" width="80" height="80"/>',
                    '<div class="list-info">',
                    '	<div class="podcast-name">{name}</div>',
                    '    <tpl if="type == \'music\'">',
                    '        <div class="music-box">',
                    '            <span class="music-icon-unplayed"></span><span class="music-date">{date}</span>',
                    '        </div>',
                    '    <tpl else>',
                    '        <div class="video-box">',
                    '            <span class="video-icon-grey"></span><span class="video-date">{date}</span>',
                    '        </div>',
                    '    </tpl>',
                    '</div>',
                    ''
                ],
                store: 'UnplayedStore',
                itemHeight: 90
            }
        ]
    }

});