/*
 * File: app/view/Episode.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Episode', {
    extend: 'Ext.Container',
    alias: 'widget.episode',

    config: {
        items: [
            {
                xtype: 'container',
                docked: 'top',
                style: 'background: #8fced6',
                items: [
                    {
                        xtype: 'container',
                        html: '<div class="episode-title">Random Access Memories Episode 3</div> <div class="music-toal-white">1 hour 12 min</div> <div class="calendar-white">12.02.2013</div>',
                        padding: '10 10 20 10'
                    },
                    {
                        xtype: 'button',
                        margin: '0 10 10 10',
                        style: 'color: #8fced6;\r\nbackground: #fff;\r\nborder:none;\r\nfont-size: 14px;',
                        text: 'Mark as Played'
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'top',
                height: '100%',
                html: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor nisi ut aliquip ex ea commodo consequat.<br/><br/> Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.',
                padding: '10 10 0 10',
                style: 'color: #555555;\r\nfont-size: 12px;',
                layout: {
                    type: 'fit'
                },
                scrollable: true
            }
        ]
    }

});