/*
 * File: app/view/LibrarySearch.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LibrarySearch', {
    extend: 'Ext.Container',
    alias: 'widget.librarysearch',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                style: 'border:none',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        itemId: 'mysearchfield2',
                        label: '',
                        name: ''
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                hidden: true,
                itemId: 'librarybar',
                style: 'border: none;\r\nbackground: #8fced6;',
                items: [
                    {
                        xtype: 'label',
                        itemId: 'podcastname_search',
                        style: 'color: #000;\r\nfont-size: 14px;',
                        ui: ''
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'btnsubscribe_search',
                        style: 'background: #fff;\r\ncolor: #8fced6;\r\nborder: none;',
                        text: 'Subscribe'
                    }
                ]
            },
            {
                xtype: 'list',
                docked: 'top',
                height: '100%',
                itemId: 'mylist3',
                style: 'font-size: 12px',
                scrollable: true,
                emptyText: 'No results',
                itemTpl: [
                    '<tpl if="episode_html != \'\'">',
                    '    <div style="min-height: 125px;">{episode_html}</div>',
                    '<tpl else>',
                    '	<img class="photo shadow" src="{episode_thumbnail}" width="60" height="60"/>',
                    '    <div class="list-info">',
                    '        <div class="podcast-name">{episode_name}</div>',
                    '        <tpl if="episode_type == 0">',
                    '            <div class="music-box">',
                    '                <span class="music-icon-unplayed"></span><span class="music-date">{episode_date:date("m.d.Y")}</span>',
                    '            </div>',
                    '        <tpl else>',
                    '            <div class="video-box">',
                    '                <span class="video-icon-grey"></span><span class="video-date">{episode_date:date("m.d.Y")}</span>',
                    '            </div>',
                    '        </tpl>',
                    '    </div>',
                    '</tpl>',
                    '    ',
                    ''
                ],
                store: 'SearchStore',
                itemHeight: 70
            }
        ],
        listeners: [
            {
                fn: 'onMysearchfield2Action',
                event: 'action',
                delegate: '#mysearchfield2'
            },
            {
                fn: 'onBtnsubscribeTap1',
                event: 'tap',
                delegate: '#btnsubscribe_search'
            }
        ]
    },

    onMysearchfield2Action: function(textfield, e, eOpts) {
        var store = Ext.StoreMgr.lookup('SearchStore');
        proxy= store.getProxy();
        proxy.setExtraParam('searchstr',textfield);
        store.load();
        if(store.getCount() > 0){
            var podcastlabel = Ext.ComponentQuery.query('#podcastname_search')[0];
            podcastlabel.setHtml("Load from Url");

            //Show toolbar after search
            var librarybar = Ext.ComponentQuery.query('#librarybar')[0];
            librarybar.show();    
        } else {
            var librarybar = Ext.ComponentQuery.query('#librarybar')[0];
            librarybar.hide();
        }

    },

    onBtnsubscribeTap1: function(button, e, eOpts) {
        alert('send subscribe');
    }

});