/*
 * File: app/view/Library.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Library', {
    extend: 'Ext.Container',
    alias: 'widget.library',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                style: 'border:none',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        label: '',
                        name: ''
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton4',
                        style: 'background: #fff;\r\ncolor: #8fced6;\r\nborder: none;',
                        text: 'URL...'
                    }
                ]
            },
            {
                xtype: 'list',
                scrollable: 'vertical',
                itemTpl: [
                    '<img class="photo shadow" src="{photo_url}" width="60" height="60"/>',
                    '<div class="list-info">',
                    '	<div class="podcast-name">{name}</div>',
                    '    <tpl if="type == \'music\'">',
                    '        <div class="music-box">',
                    '            <span class="music-icon-unplayed"></span><span class="music-date">{date}</span>',
                    '        </div>',
                    '    <tpl else>',
                    '        <div class="video-box">',
                    '            <span class="video-icon-grey"></span><span class="video-date">{date}</span>',
                    '        </div>',
                    '    </tpl>',
                    '</div>',
                    ''
                ],
                itemHeight: 70
            }
        ],
        listeners: [
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#mybutton4'
            }
        ]
    },

    onMybutton4Tap: function(button, e, eOpts) {
        var me = this;
        var nav = Ext.ComponentQuery.query('#nav')[0];
        nav.push({
            xtype: 'librarysearch',
            title: 'Search Podcast URL'
        });
    }

});