/*
 * File: app/view/MyTab.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTab', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytab',

    requires: [
        'MyApp.view.Podcast',
        'MyApp.view.Library',
        'MyApp.view.Setting'
    ],

    config: {
        tabBar: {
            docked: 'bottom',
            style: 'background: #fff;'
        },
        items: [
            {
                xtype: 'podcast',
                iconCls: 'music'
            },
            {
                xtype: 'library',
                title: 'Library',
                iconCls: 'list'
            },
            {
                xtype: 'setting',
                title: 'Setting',
                iconCls: 'settings'
            }
        ]
    }

});