/*
 * File: app/view/Podcast.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Podcast', {
    extend: 'Ext.Container',
    alias: 'widget.podcast',

    config: {
        ui: '',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'toolbar',
                flex: 1,
                docked: 'top',
                style: 'border: none;\r\nbackground: #8fced6;',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        docked: 'left',
                        width: 200,
                        label: ''
                    },
                    {
                        xtype: 'segmentedbutton',
                        centered: true,
                        disabled: false,
                        docked: 'right',
                        itemId: 'segmentbtn',
                        ui: 'light',
                        hideOnMaskTap: false,
                        scrollable: true,
                        layout: {
                            align: 'end',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'listbtn',
                                ui: 'plain',
                                iconCls: 'favorites',
                                text: ''
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'boxbtn',
                                ui: 'plain',
                                iconCls: 'action',
                                text: ''
                            }
                        ],
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var me = this;
                                    me.setPressedButtons(0);
                                },
                                event: 'initialize'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                style: 'border: none;\r\nbackground: #f25260;',
                ui: '',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        itemId: 'unplayedbtnleft',
                        style: 'color: #fff;',
                        ui: 'plain',
                        width: 214,
                        labelCls: 'x-button-label unplayedlabel',
                        text: 'Unplayed Episodes'
                    },
                    {
                        xtype: 'button',
                        itemId: 'unplayedbtnright',
                        style: 'color: #fff',
                        ui: 'plain',
                        width: 48,
                        text: '14'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                itemId: 'podcastcontent',
                ui: '',
                layout: {
                    animation: 'flip',
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'list',
                        itemId: 'mylist',
                        scrollable: 'vertical',
                        itemTpl: [
                            '<img class="photo shadow" src="{photo_url}" width="80" height="80"/>',
                            '<div class="list-info">',
                            '	<div class="podcast-name">{name}</div>',
                            '    <div class="music-toal">5</div>',
                            '    <div class="video-toal">10</div>',
                            '</div>',
                            '<div class="unplayed-label">',
                            '	<span >4</span>',
                            '</div>',
                            ''
                        ],
                        store: 'PodcastStore',
                        itemHeight: 90
                    },
                    {
                        xtype: 'dataview',
                        margin: 5,
                        ui: '',
                        scrollable: 'vertical',
                        inline: true,
                        itemTpl: [
                            '<div class="pview">',
                            '	<img class="shadow" src="{photo_url}" width="130" height="130"/>',
                            '    <div class="unplayed-label-box">',
                            '        <span >4</span>',
                            '    </div>',
                            '',
                            '</div>',
                            ''
                        ],
                        store: 'PodcastStore'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onBoxbtnTap',
                event: 'tap',
                delegate: '#boxbtn'
            }
        ]
    },

    onBoxbtnTap: function(button, e, eOpts) {
        var me = this;
        var podcastcontent = Ext.ComponentQuery.query('#podcastcontent')[0];
        podcastcontent.setActiveItem(1);
    }

});