/*
 * File: app/view/Unplayed.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Unplayed', {
    extend: 'Ext.Container',
    alias: 'widget.unplayed',

    config: {
        itemId: 'unplayedview',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                itemId: 'unplayedlist',
                scrollable: true,
                itemTpl: [
                    '<img class="photo shadow" src="{episode_thumbnail}" width="60" height="60"/>',
                    '<div class="list-info">',
                    '    <div class="podcast-name">{episode_name}</div>',
                    '    <tpl if="episode_type == 0">',
                    '        <div class="music-box">',
                    '            <span class="music-icon-unplayed"></span><span class="music-date">{episode_date:date("m.d.Y")} {episode_duration}</span>',
                    '        </div>',
                    '        <tpl else>',
                    '            <div class="video-box">',
                    '                <span class="video-icon-grey"></span><span class="video-date">{episode_date:date("m.d.Y")} {episode_duration}</span>',
                    '            </div>',
                    '        </tpl>',
                    '    </div>',
                    '',
                    '    ',
                    ''
                ],
                store: 'UnplayedStore',
                itemHeight: 70
            }
        ]
    }

});