/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#signup": {
                tap: 'onSignupTap'
            },
            "button#listbtn": {
                tap: 'onListbtnTap'
            },
            "button#unplayedbtnright": {
                tap: 'onUnplayedbtnrightTap'
            },
            "button#unplayedbtnleft": {
                tap: 'onUnplayedbtnleftTap'
            },
            "list#mylist": {
                itemtap: 'onMyPodCastTap'
            },
            "list#mylist2": {
                itemtap: 'onEpisodesTap'
            }
        }
    },

    onSignupTap: function(button, e, eOpts) {
        Ext.Viewport.setActiveItem({
            xtype: 'mainview'
        });
    },

    onListbtnTap: function(button, e, eOpts) {
        var me = this;
        var podcastcontent = Ext.ComponentQuery.query('#podcastcontent')[0];
        podcastcontent.setActiveItem(0);
    },

    onUnplayedbtnrightTap: function(button, e, eOpts) {
        var me = this;
        me.Unplayed();
    },

    onUnplayedbtnleftTap: function(button, e, eOpts) {
        var me = this;
        me.Unplayed();
    },

    onMyPodCastTap: function(dataview, index, target, record, e, eOpts) {
        var me = this;
        var nav = Ext.ComponentQuery.query('#nav')[0];
        nav.push({
            xtype: 'episodes',
            title: 'Episodes'
        });
    },

    onEpisodesTap: function(dataview, index, target, record, e, eOpts) {
        var me = this;
        var nav = Ext.ComponentQuery.query('#nav')[0];
        nav.push({
            xtype: 'episode',
            title: 'Episode Info'
        });
    },

    Unplayed: function() {
        var nav = Ext.ComponentQuery.query('#nav')[0];
        nav.push({
            xtype: 'unplayed',
            title: 'Unplayed'
        });
    }

});